import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: { fontFamily: "'Share Tech Mono', monospace", backgroundColor: '#0a0f0a', color: '#e0e0e0', height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative' },
  gridOverlay: { position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(0,255,159,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(0,255,159,0.02) 1px, transparent 1px)', backgroundSize: '40px 40px', pointerEvents: 'none', zIndex: 1 },
  scanline: { position: 'absolute', left: 0, right: 0, height: '80px', background: 'linear-gradient(to bottom, transparent, rgba(0,255,159,0.03), rgba(0,255,159,0.06), rgba(0,255,159,0.03), transparent)', animation: 'scanline 8s linear infinite', pointerEvents: 'none', zIndex: 1000 },
  crtOverlay: { position: 'absolute', inset: 0, background: 'repeating-linear-gradient(0deg, rgba(0,0,0,0.1) 0px, rgba(0,0,0,0.1) 1px, transparent 1px, transparent 2px)', pointerEvents: 'none', zIndex: 1, animation: 'flicker 0.15s infinite' },

  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 16px', borderBottom: '1px solid rgba(0,255,159,0.2)', backgroundColor: 'rgba(10,15,10,0.95)', zIndex: 10, flexShrink: 0 },
  logoSection: { display: 'flex', alignItems: 'center', gap: '10px' },
  logoIcon: {},
  logoText: { fontFamily: "'Orbitron'", fontSize: '20px', fontWeight: 900, color: '#00ff9f', margin: 0, letterSpacing: '2px' },
  logoSubtext: { fontSize: '8px', color: '#666', letterSpacing: '1px' },
  controls: { display: 'flex', alignItems: 'center', gap: '10px' },
  searchContainer: { position: 'relative' },
  searchIcon: { position: 'absolute', left: '8px', top: '50%', transform: 'translateY(-50%)', color: '#666', fontSize: '12px' },
  searchInput: { background: 'rgba(0,255,159,0.05)', border: '1px solid rgba(0,255,159,0.3)', borderRadius: '4px', padding: '6px 8px 6px 28px', color: '#00ff9f', fontFamily: 'inherit', fontSize: '11px', width: '150px', outline: 'none' },
  controlButton: { padding: '6px 14px', border: 'none', borderRadius: '4px', fontFamily: "'Orbitron'", fontSize: '10px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' },
  startButton: { background: '#00ff9f', color: '#0a0f0a' },
  stopButton: { background: '#ff3366', color: '#fff' },
  clearButton: { padding: '6px 10px', background: 'transparent', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '4px', color: '#888', fontFamily: "'Orbitron'", fontSize: '9px', cursor: 'pointer' },
  pulsingDot: { width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#fff', animation: 'pulse 1s infinite' },
  statsPreview: { display: 'flex', gap: '16px' },
  statItem: { textAlign: 'right' },
  statValue: { fontFamily: "'Orbitron'", fontSize: '16px', fontWeight: 700, color: '#00ff9f' },
  statLabel: { fontSize: '8px', color: '#666' },

  nav: { display: 'flex', borderBottom: '1px solid rgba(0,255,159,0.1)', backgroundColor: 'rgba(10,15,10,0.8)', flexShrink: 0, overflowX: 'auto' },
  navTab: { padding: '10px 14px', background: 'transparent', border: 'none', borderBottom: '2px solid transparent', color: '#666', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '5px', whiteSpace: 'nowrap' },
  navTabActive: { color: '#00ff9f', borderBottomColor: '#00ff9f' },
  navIcon: { fontSize: '11px' },

  mainContent: { flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column', minHeight: 0 },
  splitView: { display: 'flex', flex: 1, minHeight: 0 },

  routeTraceContainer: { display: 'flex', flex: 1, minHeight: 0 },
  routeStreamPanel: { width: '280px', borderRight: '1px solid rgba(0,255,159,0.1)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  routePanelHeader: { padding: '12px', borderBottom: '1px solid rgba(0,255,159,0.1)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  routePanelTitle: { fontFamily: "'Orbitron'", fontSize: '11px', color: '#00ff9f' },
  viewModeToggle: { display: 'flex', gap: '4px' },
  viewModeBtn: { padding: '4px 8px', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: '#666', fontSize: '8px', cursor: 'pointer' },
  viewModeBtnActive: { borderColor: '#00ff9f', color: '#00ff9f' },
  routeStreamList: { flex: 1, overflowY: 'auto' },
  routeEmpty: { padding: '20px', textAlign: 'center', color: '#444', fontSize: '11px' },
  routeStreamItem: { padding: '10px 12px', borderBottom: '1px solid rgba(255,255,255,0.03)', borderLeft: '3px solid', cursor: 'pointer' },
  routeStreamHeader: { display: 'flex', justifyContent: 'space-between', fontSize: '10px', marginBottom: '4px' },
  routeHopCount: { color: '#666' },
  routeStreamPath: { fontSize: '9px', color: '#888', fontFamily: 'monospace' },
  routeDetailPanel: { borderTop: '1px solid rgba(0,255,159,0.2)', padding: '12px', backgroundColor: 'rgba(0,0,0,0.2)' },
  routeDetailTitle: { fontSize: '10px', fontWeight: 'bold', marginBottom: '10px' },
  routeHopList: { fontSize: '10px' },
  routeHopItem: { display: 'flex', gap: '8px', padding: '4px 0', borderBottom: '1px solid rgba(255,255,255,0.03)' },
  hopNumber: { width: '30px', color: '#666' },
  hopIP: { flex: 1, fontFamily: 'monospace' },
  hopRtt: { color: '#ffd600', width: '50px' },
  hopType: { color: '#444', fontSize: '9px', width: '60px' },
  routeGraphContainer: { flex: 1, position: 'relative', minHeight: 0 },
  routeSvg: { position: 'absolute', inset: 0, width: '100%', height: '100%' },
  routeListView: { padding: '16px', overflowY: 'auto', height: '100%' },
  routeListItem: { padding: '12px', marginBottom: '8px', backgroundColor: 'rgba(0,255,159,0.03)', borderRadius: '4px', border: '1px solid rgba(0,255,159,0.1)' },
  routeListHeader: { display: 'flex', gap: '10px', marginBottom: '8px', fontSize: '11px' },
  routeListHops: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '4px', fontSize: '10px', fontFamily: 'monospace' },
  routeListEndpoint: { color: '#00ff9f', padding: '2px 6px', backgroundColor: 'rgba(0,255,159,0.1)', borderRadius: '3px' },
  routeListArrow: { color: '#444' },
  routeListHop: { color: '#888' },
  routeListRtt: { color: '#ffd600', fontSize: '9px', marginLeft: '4px' },
  routeLegend: { position: 'absolute', bottom: '16px', right: '16px', backgroundColor: 'rgba(10,15,10,0.9)', border: '1px solid rgba(0,255,159,0.2)', borderRadius: '4px', padding: '10px', fontSize: '9px' },
  legendTitle: { color: '#00ff9f', fontWeight: 'bold', marginBottom: '6px' },
  legendItem: { display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '3px', color: '#888' },
  legendShape: { width: '10px', height: '10px', display: 'inline-block' },

  matrixContainer: { flex: 1, padding: '16px', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  matrixHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexShrink: 0 },
  matrixTitle: { fontFamily: "'Orbitron'", fontSize: '12px', color: '#00ff9f' },
  matrixControls: { display: 'flex', gap: '4px' },
  matrixSortBtn: { padding: '4px 10px', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: '#666', fontSize: '9px', cursor: 'pointer' },
  matrixSortBtnActive: { borderColor: '#00ff9f', color: '#00ff9f' },
  matrixGrid: { flex: 1, overflow: 'auto' },
  matrixRow: { display: 'flex' },
  matrixCorner: { width: '80px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '8px', color: '#666', flexShrink: 0 },
  matrixColHeader: { width: '50px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '8px', color: '#888', transform: 'rotate(-45deg)', flexShrink: 0 },
  matrixRowHeader: { width: '80px', height: '30px', display: 'flex', alignItems: 'center', fontSize: '9px', color: '#888', fontFamily: 'monospace', flexShrink: 0 },
  matrixCell: { width: '50px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid rgba(255,255,255,0.03)', flexShrink: 0 },
  matrixScale: { display: 'flex', alignItems: 'center', gap: '8px', marginTop: '12px', fontSize: '9px', color: '#666', flexShrink: 0 },
  matrixScaleGradient: { flex: 1, height: '8px', background: 'linear-gradient(90deg, rgba(0,255,159,0.1), rgba(0,255,159,0.9))', borderRadius: '4px' },

  sankeyContainer: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 },
  sankeyHeader: { padding: '12px 16px', borderBottom: '1px solid rgba(0,255,159,0.1)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 },
  sankeyTitle: { fontFamily: "'Orbitron'", fontSize: '12px', color: '#00ff9f' },
  sankeyControls: { display: 'flex', gap: '4px' },
  sankeyBtn: { padding: '4px 10px', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: '#666', fontSize: '9px', cursor: 'pointer' },
  sankeyBtnActive: { borderColor: '#00ff9f', color: '#00ff9f' },
  sankeyGraph: { flex: 1, minHeight: 0 },

  sequenceContainer: { display: 'flex', flex: 1, minHeight: 0 },
  sequenceStreamPanel: { width: '240px', borderRight: '1px solid rgba(0,255,159,0.1)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  sequencePanelHeader: { padding: '12px', borderBottom: '1px solid rgba(0,255,159,0.1)', fontFamily: "'Orbitron'", fontSize: '11px', color: '#00ff9f' },
  sequenceStreamList: { flex: 1, overflowY: 'auto' },
  sequenceStreamItem: { padding: '10px 12px', borderBottom: '1px solid rgba(255,255,255,0.03)', borderLeft: '3px solid', cursor: 'pointer', display: 'flex', flexWrap: 'wrap', gap: '6px', alignItems: 'center' },
  sequenceStreamPkts: { marginLeft: 'auto', fontSize: '9px', color: '#666' },
  sequenceStreamIPs: { width: '100%', fontSize: '9px', color: '#888', fontFamily: 'monospace' },
  sequenceMain: { flex: 1, overflow: 'auto', minHeight: 0 },
  sequenceDiagram: { minWidth: '600px' },
  sequenceHeaders: { display: 'flex', padding: '16px', borderBottom: '1px solid rgba(0,255,159,0.1)', position: 'sticky', top: 0, backgroundColor: '#0a0f0a', zIndex: 1 },
  sequenceTimeCol: { width: '100px', fontSize: '10px', color: '#666', flexShrink: 0 },
  sequenceEndpoint: { flex: 1, display: 'flex', justifyContent: 'center' },
  sequenceEndpointBox: { padding: '8px 16px', border: '2px solid', borderRadius: '4px', backgroundColor: 'rgba(0,0,0,0.3)', textAlign: 'center', fontSize: '11px', fontFamily: 'monospace' },
  sequencePort: { fontSize: '9px', color: '#666' },
  sequenceMiddle: { width: '100px' },
  sequenceInfoCol: { width: '150px', fontSize: '10px', color: '#666', textAlign: 'right', flexShrink: 0 },
  sequenceBody: { position: 'relative', padding: '0 16px' },
  sequenceLifelines: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, pointerEvents: 'none' },
  sequenceLifeline: { position: 'absolute', top: 0, bottom: 0, width: '2px', backgroundColor: 'rgba(255,255,255,0.1)' },
  sequenceMessage: { display: 'flex', alignItems: 'center', padding: '8px 0', minHeight: '40px' },
  sequenceTimeCell: { width: '100px', fontSize: '9px', color: '#666', fontFamily: 'monospace', flexShrink: 0 },
  sequenceArrowContainer: { flex: 1, position: 'relative', height: '24px' },
  sequenceArrow: { position: 'absolute', height: '2px', display: 'flex', alignItems: 'center' },
  sequenceArrowHead: { width: 0, height: 0, borderTop: '5px solid transparent', borderBottom: '5px solid transparent', borderLeft: '8px solid', borderRight: '8px solid' },
  sequenceArrowLabel: { position: 'absolute', left: '50%', transform: 'translateX(-50%)', top: '-14px', display: 'flex', gap: '6px', fontSize: '9px' },
  sequenceFlags: { color: '#ff6b00', fontWeight: 'bold' },
  sequenceLen: { color: '#666' },
  sequenceInfoCell: { width: '150px', fontSize: '9px', color: '#555', textAlign: 'right', fontFamily: 'monospace', flexShrink: 0 },

  topologyContainer: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 },
  topologyHeader: { padding: '12px 16px', borderBottom: '1px solid rgba(0,255,159,0.1)', flexShrink: 0 },
  topologyTitle: { fontFamily: "'Orbitron'", fontSize: '12px', color: '#00ff9f' },
  topologyGraph: { flex: 1, minHeight: 0 },
  topologyLegend: { padding: '10px 16px', borderTop: '1px solid rgba(0,255,159,0.1)', fontSize: '10px', color: '#888', flexShrink: 0 },

  servicesContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  servicesHeader: { padding: '12px 16px', borderBottom: '1px solid rgba(0,255,159,0.1)', flexShrink: 0 },
  servicesTitle: { fontFamily: "'Orbitron'", fontSize: '12px', color: '#00ff9f' },
  servicesGrid: { flex: 1, padding: '16px', display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px', overflowY: 'auto' },
  serviceCard: { backgroundColor: 'rgba(0,255,159,0.03)', border: '1px solid rgba(0,255,159,0.1)', borderRadius: '6px', padding: '14px' },
  serviceHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '10px' },
  serviceName: { fontFamily: "'Orbitron'", fontSize: '12px', color: '#00ff9f' },
  servicePort: { fontSize: '10px', color: '#666', fontFamily: 'monospace' },
  serviceBar: { height: '6px', backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: '3px', overflow: 'hidden', marginBottom: '10px' },
  serviceBarFill: { height: '100%', backgroundColor: '#00ff9f', borderRadius: '3px' },
  serviceStats: { display: 'flex', justifyContent: 'space-between', marginBottom: '8px' },
  serviceStat: { textAlign: 'center' },
  serviceStatValue: { display: 'block', fontSize: '14px', color: '#fff' },
  serviceStatLabel: { fontSize: '8px', color: '#666' },
  serviceProtocols: { display: 'flex', gap: '4px', flexWrap: 'wrap' },
  serviceProtocolTag: { fontSize: '9px', padding: '2px 6px', backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: '3px' },

  packetList: { flex: 1, display: 'flex', flexDirection: 'column', borderRight: '1px solid rgba(0,255,159,0.1)', minWidth: 0 },
  tableHeader: { display: 'flex', padding: '8px 10px', backgroundColor: 'rgba(0,255,159,0.05)', borderBottom: '1px solid rgba(0,255,159,0.2)', fontFamily: "'Orbitron'", fontSize: '8px', color: '#00ff9f', flexShrink: 0 },
  tableBody: { flex: 1, overflowY: 'auto', minHeight: 0 },
  tableRow: { display: 'flex', padding: '6px 10px', borderBottom: '1px solid rgba(255,255,255,0.03)', cursor: 'pointer', fontSize: '10px' },
  tableCell: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', paddingRight: '6px' },
  flag: { display: 'inline-block', padding: '1px 4px', backgroundColor: 'rgba(255,107,0,0.2)', borderRadius: '2px', fontSize: '8px', color: '#ff6b00' },

  packetDetails: { width: '280px', backgroundColor: 'rgba(0,0,0,0.2)', overflowY: 'auto', padding: '12px', flexShrink: 0 },
  detailsHeader: { fontFamily: "'Orbitron'", fontSize: '11px', color: '#00ff9f', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' },
  detailsSection: { marginBottom: '12px', padding: '10px', backgroundColor: 'rgba(0,255,159,0.02)', borderRadius: '4px', border: '1px solid rgba(0,255,159,0.1)' },
  sectionTitle: { fontFamily: "'Orbitron'", fontSize: '9px', color: '#00ff9f', marginBottom: '8px' },
  detailRow: { display: 'flex', justifyContent: 'space-between', padding: '3px 0', fontSize: '10px', borderBottom: '1px solid rgba(255,255,255,0.03)' },

  structureContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },
  structureContent: { display: 'flex', flexDirection: 'column', gap: '12px', maxWidth: '800px', margin: '0 auto' },
  layerBox: { border: '1px solid rgba(255,255,255,0.1)', borderRadius: '6px', padding: '14px' },
  layerTitle: { fontFamily: "'Orbitron'", fontSize: '11px', marginBottom: '10px' },
  layerFields: { display: 'flex', flexWrap: 'wrap', gap: '12px', fontSize: '11px', color: '#888', fontFamily: 'monospace' },

  statsContainer: { flex: 1, padding: '16px', overflow: 'auto' },
  summaryCards: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '16px' },
  summaryCard: { backgroundColor: 'rgba(0,255,159,0.03)', border: '1px solid rgba(0,255,159,0.1)', borderRadius: '6px', padding: '14px', textAlign: 'center' },
  summaryValue: { fontFamily: "'Orbitron'", fontSize: '24px', color: '#00ff9f' },
  summaryLabel: { fontSize: '9px', color: '#666', marginTop: '4px' },
  chartCard: { backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: '6px', padding: '14px' },
  chartTitle: { fontFamily: "'Orbitron'", fontSize: '10px', color: '#00ff9f', marginBottom: '12px' },
  barRow: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' },
  barContainer: { flex: 1, height: '14px', backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: '3px', overflow: 'hidden' },
  bar: { height: '100%', borderRadius: '3px' },

  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#444', gap: '8px' },
  emptyIcon: { fontSize: '36px', color: '#333' },
  emptySubtext: { fontSize: '10px', color: '#333' },

  statusBar: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 16px', borderTop: '1px solid rgba(0,255,159,0.1)', backgroundColor: 'rgba(10,15,10,0.95)', fontSize: '9px', color: '#666', flexShrink: 0 },
  statusLeft: { display: 'flex', alignItems: 'center', gap: '6px' },
  statusIndicator: { width: '6px', height: '6px', borderRadius: '50%' },
  statusRight: { fontFamily: "'Orbitron'", letterSpacing: '1px' },

  settingsPanel: { position: 'absolute', top: '60px', right: '16px', width: '280px', backgroundColor: 'rgba(10,15,10,0.98)', border: '1px solid rgba(0,255,159,0.3)', borderRadius: '8px', zIndex: 100, boxShadow: '0 8px 32px rgba(0,0,0,0.5)', overflow: 'hidden' },
  settingsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 14px', borderBottom: '1px solid rgba(0,255,159,0.2)', backgroundColor: 'rgba(0,255,159,0.05)' },
  settingsTitle: { fontFamily: "'Orbitron'", fontSize: '11px', color: '#00ff9f', letterSpacing: '1px' },
  settingsClose: { background: 'none', border: 'none', color: '#666', fontSize: '14px', cursor: 'pointer', padding: '4px 8px' },
  settingsContent: { padding: '12px' },
  settingsGroup: { marginBottom: '16px', paddingBottom: '16px', borderBottom: '1px solid rgba(255,255,255,0.05)' },
  settingsRow: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' },
  settingsLabel: { flex: 1, fontSize: '11px', color: '#888', fontWeight: 'bold' },
  settingsSubLabel: { flex: 1, fontSize: '10px', color: '#555', paddingLeft: '8px' },
  toggleButton: { padding: '4px 12px', border: 'none', borderRadius: '4px', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 700, cursor: 'pointer', transition: 'all 0.15s' },
  slider: { flex: 1, height: '4px', WebkitAppearance: 'none', background: 'rgba(0,255,159,0.2)', borderRadius: '2px', cursor: 'pointer', accentColor: '#00ff9f' } as React.CSSProperties,
  sliderValue: { width: '36px', fontSize: '9px', color: '#00ff9f', textAlign: 'right', fontFamily: 'monospace' },
  presetButtons: { display: 'flex', gap: '6px', marginTop: '8px' },
  presetButton: { flex: 1, padding: '8px 4px', border: '1px solid rgba(0,255,159,0.3)', borderRadius: '4px', background: 'rgba(0,255,159,0.05)', color: '#00ff9f', fontFamily: "'Orbitron'", fontSize: '8px', fontWeight: 700, cursor: 'pointer', transition: 'all 0.15s' },

  // Livewire view
  livewireContainer: { display: 'flex', flex: 1, minHeight: 0 },
  livewireStreamPanel: { width: '280px', borderRight: '1px solid rgba(0,255,159,0.1)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  livewireContentArea: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0, overflow: 'hidden' },
  livewireContentHeader: { display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 14px', borderBottom: '1px solid rgba(0,255,159,0.1)', flexShrink: 0, flexWrap: 'wrap' },
  livewireProtocolBadge: { padding: '3px 10px', borderRadius: '3px', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 700 },
  livewireStats: { fontSize: '9px', color: '#666', marginLeft: 'auto' },
  livewireBody: { flex: 1, overflowY: 'auto', padding: '14px' },
  livewireCodeBlock: { fontFamily: "'Share Tech Mono', monospace", fontSize: '11px', lineHeight: '1.6', whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: '#e0e0e0', background: 'rgba(0,0,0,0.3)', borderRadius: '4px', padding: '12px', border: '1px solid rgba(255,255,255,0.05)' },
  livewireCard: { border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', marginBottom: '12px', overflow: 'hidden' },
  livewireCardHeader: { display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 12px', fontSize: '10px', fontWeight: 700 },
  livewireCardBody: { padding: '12px', fontSize: '11px', fontFamily: "'Share Tech Mono', monospace", lineHeight: '1.5' },
  livewireEncrypted: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '12px', color: '#666' },
  livewireTerminal: { fontFamily: "'Share Tech Mono', monospace", fontSize: '11px', lineHeight: '1.6', whiteSpace: 'pre-wrap', color: '#00ff9f', background: '#0a0a0a', borderRadius: '4px', padding: '14px', border: '1px solid rgba(0,255,159,0.15)', minHeight: '200px' },
};
