import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: { fontFamily: "'Share Tech Mono', monospace", backgroundColor: 'var(--bg-primary)', color: 'var(--text-primary)', fontWeight: 'var(--font-weight)' as unknown as number, height: '100vh', display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative' },

  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 16px', borderBottom: '1px solid var(--border-strong)', backgroundColor: 'var(--header-bg)', zIndex: 10, flexShrink: 0 },
  logoSection: { display: 'flex', alignItems: 'center', gap: '10px' },
  logoIcon: {},
  logoText: { fontFamily: "'Orbitron'", fontSize: '20px', fontWeight: 900, color: 'var(--accent)', margin: 0, letterSpacing: '2px' },
  logoSubtext: { fontSize: '9px', color: 'var(--text-secondary)', letterSpacing: '1px', fontWeight: 600 },
  controls: { display: 'flex', alignItems: 'center', gap: '10px' },
  searchContainer: { position: 'relative' },
  searchIcon: { position: 'absolute', left: '8px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', fontSize: '12px' },
  searchInput: { background: 'var(--bg-surface)', border: '1px solid rgba(var(--accent-rgb),0.3)', borderRadius: '4px', padding: '6px 8px 6px 28px', color: 'var(--accent)', fontFamily: 'inherit', fontSize: '11px', width: '150px', outline: 'none' },
  controlButton: { padding: '6px 14px', border: 'none', borderRadius: '4px', fontFamily: "'Orbitron'", fontSize: '10px', fontWeight: 800, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' },
  startButton: { background: 'var(--accent)', color: 'var(--bg-primary)' },
  stopButton: { background: '#ff3366', color: '#fff' },
  clearButton: { padding: '6px 10px', background: 'transparent', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '4px', color: 'var(--text-secondary)', fontFamily: "'Orbitron'", fontSize: '9px', cursor: 'pointer' },
  pulsingDot: { width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#fff', animation: 'pulse 1s infinite' },
  statsPreview: { display: 'flex', gap: '16px' },
  statItem: { textAlign: 'right' },
  statValue: { fontFamily: "'Orbitron'", fontSize: '16px', fontWeight: 900, color: 'var(--accent)' },
  statLabel: { fontSize: '9px', fontWeight: 600, color: 'var(--text-secondary)' },

  nav: { display: 'flex', gap: '2px', padding: '0 8px', borderBottom: '1px solid var(--border)', backgroundColor: 'var(--header-bg)', backdropFilter: 'blur(8px)', flexShrink: 0, overflowX: 'auto', scrollbarWidth: 'none', alignItems: 'stretch' },
  navTab: { padding: '10px 16px', backgroundColor: 'transparent', border: 'none', borderBottomWidth: '2px', borderBottomStyle: 'solid', borderBottomColor: 'transparent', color: 'var(--text-dim)', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 800, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', whiteSpace: 'nowrap', transition: 'all 0.25s ease', letterSpacing: '0.5px' },
  navTabHover: { color: 'var(--accent)', backgroundColor: 'var(--bg-hover)', textShadow: '0 0 8px rgba(var(--accent-rgb),0.4)', borderBottomColor: 'rgba(var(--accent-rgb),0.3)' },
  navTabActive: { color: 'var(--accent)', borderBottomColor: 'var(--accent)', backgroundColor: 'rgba(var(--accent-rgb),0.08)', textShadow: '0 0 12px rgba(var(--accent-rgb),0.6)', boxShadow: '0 2px 8px rgba(var(--accent-rgb),0.3)' },
  navIcon: { fontSize: '11px', transition: 'all 0.25s ease' },
  navIconHover: { filter: 'drop-shadow(0 0 4px rgba(var(--accent-rgb),0.5))', transform: 'scale(1.15)' },
  navIconActive: { filter: 'drop-shadow(0 0 6px rgba(var(--accent-rgb),0.7))' },
  navSeparator: { width: '1px', alignSelf: 'center', height: '16px', backgroundColor: 'rgba(255,255,255,0.08)', flexShrink: 0 },

  mainContent: { flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column', minHeight: 0 },
  splitView: { display: 'flex', flex: 1, minHeight: 0 },

  routeTraceContainer: { display: 'flex', flex: 1, minHeight: 0 },
  routeStreamPanel: { width: '280px', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  routePanelHeader: { padding: '12px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  routePanelTitle: { fontFamily: "'Orbitron'", fontSize: '11px', fontWeight: 800, color: 'var(--accent)' },
  viewModeToggle: { display: 'flex', gap: '4px' },
  viewModeBtn: { padding: '4px 8px', borderWidth: '1px', borderStyle: 'solid', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: 'var(--text-muted)', fontSize: '8px', cursor: 'pointer' },
  viewModeBtnActive: { borderColor: 'var(--accent)', color: 'var(--accent)' },
  routeStreamList: { flex: 1, overflowY: 'auto' },
  routeEmpty: { padding: '20px', textAlign: 'center', color: 'var(--text-faint)', fontSize: '11px' },
  routeStreamItem: { padding: '10px 12px', borderBottom: '1px solid rgba(255,255,255,0.03)', borderLeft: '3px solid', cursor: 'pointer' },
  routeStreamHeader: { display: 'flex', justifyContent: 'space-between', fontSize: '10px', marginBottom: '4px' },
  routeHopCount: { color: 'var(--text-muted)' },
  routeStreamPath: { fontSize: '9px', color: 'var(--text-secondary)', fontFamily: 'monospace' },
  routeDetailPanel: { borderTop: '1px solid var(--border-strong)', padding: '12px', backgroundColor: 'var(--bg-secondary)' },
  routeDetailTitle: { fontSize: '11px', fontWeight: 700, marginBottom: '10px' },
  routeHopList: { fontSize: '10px' },
  routeHopItem: { display: 'flex', gap: '8px', padding: '4px 0', borderBottom: '1px solid rgba(255,255,255,0.03)' },
  hopNumber: { width: '30px', color: 'var(--text-muted)' },
  hopIP: { flex: 1, fontFamily: 'monospace' },
  hopRtt: { color: '#ffd600', width: '50px' },
  hopType: { color: 'var(--text-faint)', fontSize: '9px', width: '60px' },
  routeGraphContainer: { flex: 1, position: 'relative', minHeight: 0 },
  routeSvg: { position: 'absolute', inset: 0, width: '100%', height: '100%' },
  routeListView: { padding: '16px', overflowY: 'auto', height: '100%' },
  routeListItem: { padding: '12px', marginBottom: '8px', backgroundColor: 'var(--bg-surface)', borderRadius: '4px', border: '1px solid var(--border)' },
  routeListHeader: { display: 'flex', gap: '10px', marginBottom: '8px', fontSize: '11px' },
  routeListHops: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '4px', fontSize: '10px', fontFamily: 'monospace' },
  routeListEndpoint: { color: 'var(--accent)', padding: '2px 6px', backgroundColor: 'rgba(var(--accent-rgb),0.1)', borderRadius: '3px' },
  routeListArrow: { color: 'var(--text-faint)' },
  routeListHop: { color: 'var(--text-secondary)' },
  routeListRtt: { color: '#ffd600', fontSize: '9px', marginLeft: '4px' },
  legendItem: { display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '3px', color: 'var(--text-secondary)' },
  legendShape: { width: '10px', height: '10px', display: 'inline-block' },

  matrixContainer: { flex: 1, padding: '16px', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  matrixHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexShrink: 0 },
  matrixTitle: { fontFamily: "'Orbitron'", fontSize: '12px', fontWeight: 800, color: 'var(--accent)' },
  matrixControls: { display: 'flex', gap: '4px' },
  matrixSortBtn: { padding: '4px 10px', borderWidth: '1px', borderStyle: 'solid', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: 'var(--text-muted)', fontSize: '9px', cursor: 'pointer' },
  matrixSortBtnActive: { borderColor: 'var(--accent)', color: 'var(--accent)' },
  matrixGrid: { flex: 1, overflow: 'auto' },
  matrixRow: { display: 'flex' },
  matrixCorner: { width: '80px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '8px', color: 'var(--text-muted)', flexShrink: 0 },
  matrixColHeader: { width: '50px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '8px', color: 'var(--text-secondary)', transform: 'rotate(-45deg)', flexShrink: 0 },
  matrixRowHeader: { width: '80px', height: '30px', display: 'flex', alignItems: 'center', fontSize: '9px', color: 'var(--text-secondary)', fontFamily: 'monospace', flexShrink: 0 },
  matrixCell: { width: '50px', height: '30px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid rgba(255,255,255,0.03)', flexShrink: 0 },
  matrixScale: { display: 'flex', alignItems: 'center', gap: '8px', marginTop: '12px', fontSize: '9px', color: 'var(--text-muted)', flexShrink: 0 },
  matrixScaleGradient: { flex: 1, height: '8px', background: 'linear-gradient(90deg, rgba(var(--accent-rgb),0.1), rgba(var(--accent-rgb),0.9))', borderRadius: '4px' },

  sankeyContainer: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 },
  sankeyHeader: { padding: '12px 16px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 },
  sankeyTitle: { fontFamily: "'Orbitron'", fontSize: '12px', fontWeight: 800, color: 'var(--accent)' },
  sankeyControls: { display: 'flex', gap: '4px' },
  sankeyBtn: { padding: '4px 10px', borderWidth: '1px', borderStyle: 'solid', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '3px', background: 'transparent', color: 'var(--text-muted)', fontSize: '9px', cursor: 'pointer' },
  sankeyBtnActive: { borderColor: 'var(--accent)', color: 'var(--accent)' },
  sankeyGraph: { flex: 1, minHeight: 0 },

  sequenceContainer: { display: 'flex', flex: 1, minHeight: 0, overflow: 'hidden' },
  sequenceStreamPanel: { width: '240px', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  sequencePanelHeader: { padding: '12px', borderBottom: '1px solid var(--border)', fontFamily: "'Orbitron'", fontSize: '11px', fontWeight: 800, color: 'var(--accent)' },
  sequenceStreamList: { flex: 1, overflowY: 'auto' },
  sequenceStreamItem: { padding: '10px 12px', borderBottom: '1px solid rgba(255,255,255,0.03)', borderLeft: '3px solid', cursor: 'pointer', display: 'flex', flexWrap: 'wrap', gap: '6px', alignItems: 'center' },
  sequenceStreamPkts: { marginLeft: 'auto', fontSize: '9px', color: 'var(--text-muted)' },
  sequenceStreamIPs: { width: '100%', fontSize: '9px', color: 'var(--text-secondary)', fontFamily: 'monospace' },
  sequenceMain: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0, overflow: 'hidden' },

  topologyContainer: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 },
  topologyHeader: { padding: '12px 16px', borderBottom: '1px solid var(--border)', flexShrink: 0 },
  topologyTitle: { fontFamily: "'Orbitron'", fontSize: '12px', fontWeight: 800, color: 'var(--accent)' },
  topologyGraph: { flex: 1, minHeight: 0 },

  servicesContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  servicesHeader: { padding: '12px 16px', borderBottom: '1px solid var(--border)', flexShrink: 0 },
  servicesTitle: { fontFamily: "'Orbitron'", fontSize: '12px', fontWeight: 800, color: 'var(--accent)' },
  servicesGrid: { flex: 1, padding: '16px', display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px', overflowY: 'auto' },
  serviceCard: { backgroundColor: 'var(--bg-surface)', border: '1px solid var(--border)', borderRadius: '6px', padding: '14px' },
  serviceHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '10px' },
  serviceName: { fontFamily: "'Orbitron'", fontSize: '12px', fontWeight: 800, color: 'var(--accent)' },
  servicePort: { fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'monospace' },
  serviceBar: { height: '6px', backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: '3px', overflow: 'hidden', marginBottom: '10px' },
  serviceBarFill: { height: '100%', backgroundColor: 'var(--accent)', borderRadius: '3px' },
  serviceStats: { display: 'flex', justifyContent: 'space-between', marginBottom: '8px' },
  serviceStat: { textAlign: 'center' },
  serviceStatValue: { display: 'block', fontSize: '14px', fontWeight: 700, color: 'var(--text-primary)' },
  serviceStatLabel: { fontSize: '9px', fontWeight: 600, color: 'var(--text-muted)' },
  serviceProtocols: { display: 'flex', gap: '4px', flexWrap: 'wrap' },
  serviceProtocolTag: { fontSize: '9px', padding: '2px 6px', backgroundColor: 'var(--bg-secondary)', borderRadius: '3px' },

  packetList: { flex: 1, display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border)', minWidth: 0 },
  tableHeader: { display: 'flex', padding: '8px 10px', backgroundColor: 'var(--bg-surface)', borderBottom: '1px solid var(--border-strong)', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 800, color: 'var(--accent)', flexShrink: 0 },
  tableBody: { flex: 1, overflowY: 'auto', minHeight: 0 },
  tableRow: { display: 'flex', padding: '6px 10px', borderBottom: '1px solid rgba(255,255,255,0.03)', cursor: 'pointer', fontSize: '11px', fontWeight: 'var(--font-weight)' as unknown as number },
  tableCell: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', paddingRight: '6px' },
  flag: { display: 'inline-block', padding: '1px 4px', backgroundColor: 'rgba(255,107,0,0.2)', borderRadius: '2px', fontSize: '8px', color: '#ff6b00' },

  packetDetails: { width: '280px', backgroundColor: 'var(--bg-secondary)', overflowY: 'auto', padding: '12px', flexShrink: 0 },
  detailsHeader: { fontFamily: "'Orbitron'", fontSize: '11px', fontWeight: 800, color: 'var(--accent)', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px' },
  detailsSection: { marginBottom: '12px', padding: '10px', backgroundColor: 'rgba(var(--accent-rgb),0.02)', borderRadius: '4px', border: '1px solid var(--border)' },
  sectionTitle: { fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 800, color: 'var(--accent)', marginBottom: '8px' },
  detailRow: { display: 'flex', justifyContent: 'space-between', padding: '3px 0', fontSize: '11px', fontWeight: 'var(--font-weight)' as unknown as number, borderBottom: '1px solid rgba(255,255,255,0.03)' },

  structureContainer: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 },

  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-faint)', gap: '8px' },
  emptyIcon: { fontSize: '36px', color: 'var(--text-faint)' },
  emptySubtext: { fontSize: '10px', color: 'var(--text-faint)' },

  statusBar: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 16px', borderTop: '1px solid var(--border)', backgroundColor: 'var(--header-bg)', fontSize: '10px', fontWeight: 600, color: 'var(--text-secondary)', flexShrink: 0 },
  statusLeft: { display: 'flex', alignItems: 'center', gap: '6px' },
  statusIndicator: { width: '6px', height: '6px', borderRadius: '50%' },
  statusRight: { fontFamily: "'Orbitron'", fontWeight: 700, letterSpacing: '1px' },

  settingsPanel: { position: 'absolute', top: '60px', right: '16px', width: '280px', backgroundColor: 'var(--header-bg)', border: '1px solid rgba(var(--accent-rgb),0.3)', borderRadius: '8px', zIndex: 100, boxShadow: '0 8px 32px rgba(0,0,0,0.5)', overflow: 'hidden' },
  settingsHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 14px', borderBottom: '1px solid var(--border-strong)', backgroundColor: 'var(--bg-surface)' },
  settingsTitle: { fontFamily: "'Orbitron'", fontSize: '11px', fontWeight: 800, color: 'var(--accent)', letterSpacing: '1px' },
  settingsClose: { background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '14px', cursor: 'pointer', padding: '4px 8px' },
  settingsContent: { padding: '12px' },
  settingsGroup: { marginBottom: '16px', paddingBottom: '16px', borderBottom: '1px solid rgba(255,255,255,0.05)' },
  settingsRow: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' },
  settingsLabel: { flex: 1, fontSize: '11px', color: 'var(--text-primary)', fontWeight: 700 },
  settingsSubLabel: { flex: 1, fontSize: '10px', color: 'var(--text-dim)', paddingLeft: '8px' },
  toggleButton: { padding: '4px 12px', border: 'none', borderRadius: '4px', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 800, cursor: 'pointer', transition: 'all 0.15s' },
  slider: { flex: 1, height: '4px', WebkitAppearance: 'none', background: 'rgba(var(--accent-rgb),0.2)', borderRadius: '2px', cursor: 'pointer', accentColor: 'var(--accent)' } as React.CSSProperties,
  sliderValue: { width: '36px', fontSize: '9px', color: 'var(--accent)', textAlign: 'right', fontFamily: 'monospace' },

  // Livewire view
  livewireContainer: { display: 'flex', flex: 1, minHeight: 0 },
  livewireStreamPanel: { width: '280px', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 },
  livewireContentArea: { flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0, overflow: 'hidden' },
  livewireContentHeader: { display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 14px', borderBottom: '1px solid var(--border)', flexShrink: 0, flexWrap: 'wrap' },
  livewireProtocolBadge: { padding: '3px 10px', borderRadius: '3px', fontFamily: "'Orbitron'", fontSize: '9px', fontWeight: 800 },
  livewireStats: { fontSize: '9px', color: 'var(--text-muted)', marginLeft: 'auto' },
  livewireBody: { flex: 1, overflowY: 'auto', padding: '14px' },
  livewireCodeBlock: { fontFamily: "'Share Tech Mono', monospace", fontSize: '12px', lineHeight: '1.6', fontWeight: 'var(--font-weight)' as unknown as number, whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: 'var(--text-primary)', background: 'var(--bg-console)', borderRadius: '4px', padding: '12px', border: '1px solid rgba(255,255,255,0.05)' },
  livewireCard: { border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', marginBottom: '12px', overflow: 'hidden' },
  livewireCardHeader: { display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 12px', fontSize: '11px', fontWeight: 800 },
  livewireCardBody: { padding: '12px', fontSize: '12px', fontFamily: "'Share Tech Mono', monospace", fontWeight: 'var(--font-weight)' as unknown as number, lineHeight: '1.5' },
  livewireEncrypted: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '12px', color: 'var(--text-muted)' },
  livewireTerminal: { fontFamily: "'Share Tech Mono', monospace", fontSize: '12px', lineHeight: '1.6', fontWeight: 'var(--font-weight)' as unknown as number, whiteSpace: 'pre-wrap', color: 'var(--accent)', background: 'var(--bg-console)', borderRadius: '4px', padding: '14px', border: '1px solid rgba(var(--accent-rgb),0.15)', minHeight: '200px' },
};
